plugins {
    id 'fabric-loom' version "${loom_version}"
    id 'maven-publish'
}

repositories {
    mavenCentral()
    maven {
        url = "https://maven.fabricmc.net/"
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings "net.fabricmc:yarn:${yarn_mappings}:v2"

    modImplementation "net.fabricmc:fabric-loader:${loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"

    // ONNX Runtime
    implementation 'com.microsoft.onnxruntime:onnxruntime:1.29.0'
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

// Put ONNX Runtime inside the final mod JAR.
jar {
    from {
        configurations.runtimeClasspath.collect { file ->
            file.isDirectory() ? file : zipTree(file)
        }
    }

    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    exclude "META-INF/*.SF"
    exclude "META-INF/*.RSA"
    exclude "META-INF/*.DSA"
}

tasks.remapJar {
    dependsOn tasks.jar
}

group = project.maven_group
version = project.mod_version

base {
    archivesName = project.archives_base_name
}